- name: Installation du serveur
  hosts: all
  tasks:
    - name: Execute the command in remot
      shell: useradd test4 -m -s /bin/bash -p itescia
    - name: Execute the command in remot
      shell: passwd test4
    - name: Execute the command in remot
      shell: itescia
    - name: Execute the command in remot
      shell: itescia
