- name: Installation du serveur
  hosts: all
  vars: 
    list:
     - '192.168.56.129'
     - '192.168.56.130'
     - '192.168.56.131'   
    mdp: "itescia"
tasks:
    - name: Execute the command in remot
      shell: ssh_copy-id itesciadmin@"{{ item }}" 
      loop : "{{ list }} "
